package hibernate;
// Generated 23-feb-2015 14:14:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private Integer id;
     private BigDecimal precio;
     private String direccion;
     private String tipo;
     private String localidad;
     private String usuario;
     private Set fotoses = new HashSet(0);

    public Inmueble() {
    }

	
    public Inmueble(BigDecimal precio, String direccion, String tipo, String localidad, String usuario) {
        this.precio = precio;
        this.direccion = direccion;
        this.tipo = tipo;
        this.localidad = localidad;
        this.usuario = usuario;
    }
    public Inmueble(BigDecimal precio, String direccion, String tipo, String localidad, String usuario, Set fotoses) {
       this.precio = precio;
       this.direccion = direccion;
       this.tipo = tipo;
       this.localidad = localidad;
       this.usuario = usuario;
       this.fotoses = fotoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Set getFotoses() {
        return this.fotoses;
    }
    
    public void setFotoses(Set fotoses) {
        this.fotoses = fotoses;
    }




}


